// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2v48XUDMsOdq_oJpcnbeYBRoHVxfkXyM',
    appId: '1:202473710199:web:9037f3a6f5ab1fde791c72',
    messagingSenderId: '202473710199',
    projectId: 'acompanhamentoalunosespeciais',
    authDomain: 'acompanhamentoalunosespeciais.firebaseapp.com',
    storageBucket: 'acompanhamentoalunosespeciais.firebasestorage.app',
    measurementId: 'G-DY1WF15SDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8P9pkjhV5RNyHGeUIEzSooIY56iwcLI',
    appId: '1:202473710199:android:b08b954fcc821e6c791c72',
    messagingSenderId: '202473710199',
    projectId: 'acompanhamentoalunosespeciais',
    storageBucket: 'acompanhamentoalunosespeciais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAziBcf7u6YEB_Z4vCnNK_S1KYR5ZDfU',
    appId: '1:202473710199:ios:23d23cff86ef4895791c72',
    messagingSenderId: '202473710199',
    projectId: 'acompanhamentoalunosespeciais',
    storageBucket: 'acompanhamentoalunosespeciais.firebasestorage.app',
    iosBundleId: 'com.example.desafioMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACAziBcf7u6YEB_Z4vCnNK_S1KYR5ZDfU',
    appId: '1:202473710199:ios:23d23cff86ef4895791c72',
    messagingSenderId: '202473710199',
    projectId: 'acompanhamentoalunosespeciais',
    storageBucket: 'acompanhamentoalunosespeciais.firebasestorage.app',
    iosBundleId: 'com.example.desafioMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2v48XUDMsOdq_oJpcnbeYBRoHVxfkXyM',
    appId: '1:202473710199:web:9a0b26a2a3cf66b4791c72',
    messagingSenderId: '202473710199',
    projectId: 'acompanhamentoalunosespeciais',
    authDomain: 'acompanhamentoalunosespeciais.firebaseapp.com',
    storageBucket: 'acompanhamentoalunosespeciais.firebasestorage.app',
    measurementId: 'G-EYLPKN6GZM',
  );
}
